-- MySQL Script generated by MySQL Workbench
-- Fri Mar 15 23:40:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restorefr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restorefr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restorefr` DEFAULT CHARACTER SET utf8 ;
USE `restorefr` ;

-- -----------------------------------------------------
-- Table `restorefr`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`status` (
  `id_status` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX `id_status_UNIQUE` (`id_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restorefr`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(105) NULL,
  `prenom` VARCHAR(105) NULL,
  `mail` VARCHAR(255) NULL,
  `password` VARCHAR(225) NULL,
  `date_inscrp` DATETIME NULL,
  `status_id_status` INT NOT NULL,
  PRIMARY KEY (`id_users`),
  INDEX `fk_users_status_idx` (`status_id_status` ASC),
  CONSTRAINT `fk_users_status`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `restorefr`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restorefr`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`categories` (
  `id_catg` INT NOT NULL,
  `categories` VARCHAR(105) NULL,
  PRIMARY KEY (`id_catg`),
  UNIQUE INDEX `id_catg_UNIQUE` (`id_catg` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restorefr`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`articles` (
  `id_articles` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(105) NULL,
  `descrpt` MEDIUMTEXT NULL,
  `article` LONGTEXT NULL,
  `url_article` VARCHAR(255) NULL,
  `categories_id_catg` INT NOT NULL,
  PRIMARY KEY (`id_articles`),
  INDEX `fk_articles_categories1_idx` (`categories_id_catg` ASC),
  CONSTRAINT `fk_articles_categories1`
    FOREIGN KEY (`categories_id_catg`)
    REFERENCES `restorefr`.`categories` (`id_catg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restorefr`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`news` (
  `id_news` INT NOT NULL,
  `titre` VARCHAR(105) NULL,
  `content` LONGTEXT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `lieux` VARCHAR(105) NULL,
  `liens` VARCHAR(255) NULL,
  PRIMARY KEY (`id_news`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restorefr`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`images` (
  `id_images` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `url_img` VARCHAR(45) NULL,
  `articles_id_articles` INT NULL,
  `news_id_news` INT NULL,
  PRIMARY KEY (`id_images`),
  INDEX `fk_images_articles1_idx` (`articles_id_articles` ASC),
  INDEX `fk_images_news1_idx` (`news_id_news` ASC),
  CONSTRAINT `fk_images_articles1`
    FOREIGN KEY (`articles_id_articles`)
    REFERENCES `restorefr`.`articles` (`id_articles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_news1`
    FOREIGN KEY (`news_id_news`)
    REFERENCES `restorefr`.`news` (`id_news`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restorefr`.`mailing_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restorefr`.`mailing_list` (
  `id_mail` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NULL,
  `date_inscrp` DATE NULL,
  PRIMARY KEY (`id_mail`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
